### ISSUE TITLE
Random occuring issue.

### ISSUE THREAD

**Issue by gitstatus1** [riflosnake/HumanCursor#14]
Hello, thanks for this fantastic library. I am currently using this package to automate some clicking on a website. This website involves clicking through a large number of pages therefore, this package comes in very useful for the automation.

However, I am currently running into some problems where it occurs at random times, unfortunately, I am unable to reproduce the exact situation that produces this error but this error has consistently stopped my program at different and random times of traversing through the webpage. Nevertheless, the error message is as shown as below.

```
 File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\humancursor\system_cursor.py", line 36, in move_to
    human_curve = HumanizeMouseTrajectory(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\humancursor\utilities\human_curve_generator.py", line 11, in __init__
    self.points = self.generate_curve(**kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\humancursor\utilities\human_curve_generator.py", line 40, in generate_curve
    internalKnots = self.generate_internal_knots(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\humancursor\utilities\human_curve_generator.py", line 78, in generate_internal_knots
    knotsY = np.random.choice(
             ^^^^^^^^^^^^^^^^^
  File "numpy\\random\\mtrand.pyx", line 951, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```

I hope you are able to help me with this issue.

**Comment by riflosnake** [comment]
Hi,

Thank you for the good comments!

Im aware that this package has some issues.

Im no longer working on it, but this issue triggered me. So only by checking this on mobile, I think I found the solution.

_My hypothesis_:

**_Circumstances_** =>

The error occurs when it tries to make a move from A to B, where either `A or B are in 20% outer boundary of the screen` (close to the screen) or `very close to each other`, **AND** either `horizontally or vertically they are identical` (e.g A has x coordinate of 56, and B does too)

**_Problem_** =>

As no offset is being added to them ( first condition ), and they are identical ( second condition ), then `range(x, y)`, fails to provide a non-empty array. And when the array comes empty, the `np.choice` function throws uncaught error. 

This is just caused by poorly written code, should have been handled.

But, I just pushed a quick commit, where instead of sometimes making the offsets 0, I changed them to 1, which ensures the boundaries will always have some difference.

Please pull the latest `main` branch or replicate the latest commit I made and try it out now, and let me know if this was the problem and its fixed.

**Comment by gitstatus1** [comment]
Thank you so much! I am giving it a test run now and see how it goes.
