### ISSUE TITLE
No relative move for system cursor?

### ISSUE THREAD

**Issue by cforcomputer** [riflosnake/HumanCursor#9]
Or am I missing something?

**Comment by riflosnake** [comment]
Relative position in WebCursor is the position within WebElement relative to its boundaries, x and y axes, starting [0, 0] at top left corner, and [1.0, 1.0] at bottom right corner.

In SystemCursor, there are no elements, or at least for my knowledge, thus there can't be any relative position to anything. (except screen size but that is not really different).

If you have any other questions or feedback about the movement in the WebCursor (I think it has worsened because of altered package dependencies I use), let me know.

**Comment by cforcomputer** [comment]
Maybe I'm having a brain fart but I need relative current position offset with humanized movement. You have `move_to` which moves to a specific coordinate on the screen, but I need to move at an offset from the current mouse position to an area of the screen within a certain bound. But that area of the screen can be anywhere on the screen and moves dynamically depending on the present elements (not web, on an application). So then, cursor.moveto does not work for that case.

I need `pyautogui.moveRel(xOffset, yOffset)`. I can add it if you don't want to. However I ran into an issue where I couldn't get your main version working in github out of the box, only the release version works without breaking. I don't want to take the time to debug right now

**Comment by riflosnake** [comment]
Oh, im having a brain fart.

Yes you are right, its not an option.

I can add it later, im a little busy these days.

Also, get the package from pip!

**Comment by cforcomputer** [comment]
I understand. I will attempt to get it working and submit a pull request, however it will be from the release version if I get it working. If you could make a release branch I could submit to that instead
